mill_radius = 3.175 / 2

# Panel outline
width = 117
right_height = 135
left_height = 95
right_width = 39
big_arc = 7.5
small_arc = 2

screw_distance_from_side = 7
screw_outer_diameter = 7
screw_inner_diameter = 4  # TODO

ldg_gear_height = 20
ldg_gear_width = 60
ldg_gear_top_margin = 14

brake_fan_width = 20
brake_fan_height = 20

ab_left_width = 40
ab_right_width = 20
ab_height = 20
ab_spacing = 7
ab_left_margin = 9
ab_top_margin = ldg_gear_top_margin + ldg_gear_height + 20

askid_right_margin = 20
askid_inner_radius = 5 # TODO
askid_outer_radius = 10

terr_bottom_margin = 11
terr_right_margin = 9
terr_width = 20
terr_height = 20